export type AlbumInfo = { name: string; id: number };

export type AlbumTrivia = {
  id: number;
  fact: string;
};

export const albumNamesHardcoded: AlbumInfo[] = [
  { name: "Please Please Me (1963)", id: 1 },
  { name: "With The Beatles (1963)", id: 2 },
  { name: "A Hard Day's Night (1964)", id: 3 },
  { name: "Beatles For Sale (1964)", id: 4 },
  { name: "Help! (1965)", id: 5 },
  { name: "Rubber Soul (1965)", id: 6 },
  { name: "Revolver (1966)", id: 7 },
  { name: "Sgt Pepper's Lonely Hearts Club Band (1967)", id: 8 },
  { name: "The Beatles (White Album) (1968)", id: 9 },
  { name: "Yellow Submarine (1969)", id: 10 },
  { name: "Abbey Road (1969)", id: 11 },
  { name: "Let It Be (1970)", id: 12 },
  { name: "13 (1971)", id: 13 },
];

// ALbum trivia generated by chatGPT, not neccessarily accurate
export const albumTrivia: AlbumTrivia[] = [
  {
    id: 1,
    fact: "This album was recorded in less than 13 hours in 1963.",
  },
  {
    id: 2,
    fact: "With The Beatles was released only seven months after their debut. (Common trivia among Beatles fans.)",
  },
  {
    id: 3,
    fact: "A Hard Day's Night contains all original compositions — no covers. (A Beatles milestone.)",
  },
  {
    id: 4,
    fact: "Beatles For Sale reflects the band's fatigue from constant touring. (Often discussed by critics.)",
  },
  {
    id: 5,
    fact: "Help! was the first Beatles album to feature orchestral instrumentation (on 'Yesterday').",
  },
  {
    id: 6,
    fact: "Rubber Soul marked a shift towards more introspective songwriting and folk influence.",
  },
  {
    id: 7,
    fact: "Revolver features 'Tomorrow Never Knows,' which used tape loops and reversed audio.",
  },
  {
    id: 8,
    fact: "Sgt Pepper's Lonely Hearts Club Band was designed to be heard as a single continuous performance.",
  },
  {
    id: 9,
    fact: "The White Album contains a wide variety of styles, from avant-garde to folk to rock.",
  },
  {
    id: 10,
    fact: "Yellow Submarine includes songs from the animated film of the same name.",
  },
  {
    id: 11,
    fact: "Abbey Road's cover shows the Beatles crossing the road outside EMI Studios.",
  },
  {
    id: 12,
    fact: "Let It Be was released after the band's break-up, even though most was recorded earlier.",
  },
  {
    id: 13,
    fact: "13 is a compilation album that brings together various Beatles tracks chronologically.",
  },
];
